library("Matrix")
library("arules")
#setwd("C:/Users/201402/Desktop/titanic")
titanic<-read.transactions(“titanic.csv",format="basket",sep=",",rm.duplicates=TRUE)
#inspect(titanic[1:5])
frequentsets=eclat(titanic,parameter=list(support=0.05,maxlen=6))
inspect(sort(frequentsets)[1:10]) 
rules = apriori(titanic,parameter = list(support = 0.01,confidence = 0.2)) 
summary(rules)
#inspect(sort(rules,by="support")[1:10])
#inspect(sort(rules,by="confidence")[1:10])
inspect(sort(rules,by="lift")[1:10])